const LS_MEMBERS='memberhub_members_v1';
const LS_SETTINGS='memberhub_settings_v1';
const DEFAULT_SETTINGS={companyName:'我的機構',password:'1234',manualNumber:false,prefix:'MEM',startNumber:1,currentSequence:1,includeYear:true,includeMonth:false,declaration1:'本人聲明以上資料真確無誤。',declaration2:'本人同意機構按服務需要保存及使用本人提供的資料。'};
let page='home', editing=null, preview=null, lockedSignature='', signatureReady=false;
const $=s=>document.querySelector(s);
const app=$('#app');
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
let members=load(LS_MEMBERS,[]);
let settings={...DEFAULT_SETTINGS,...load(LS_SETTINGS,{})};
function today(){return new Date().toISOString().slice(0,10)}
function ym(d){return (d||today()).slice(0,7)}
function age(d){if(!d)return'';const b=new Date(d),n=new Date();let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a>=0?a:''}
function nextNo(){if(settings.manualNumber)return'';const seq=String(settings.currentSequence||settings.startNumber||1).padStart(4,'0');const y=settings.includeYear?new Date().getFullYear()+'-':'';const m=settings.includeMonth?String(new Date().getMonth()+1).padStart(2,'0')+'-':'';return `${settings.prefix||'MEM'}-${y}${m}${seq}`}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nav(){return `<div class="nav no-print"><button class="${page==='home'?'active':''}" onclick="go('home')">首頁</button><button class="${page==='register'?'active':''}" onclick="go('register')">登記</button><button class="${page==='members'?'active':''}" onclick="go('members')">會員</button><button class="${page==='settings'?'active':''}" onclick="go('settings')">設定</button></div>`}
function go(p){page=p;editing=null;preview=null;lockedSignature='';signatureReady=false;render()}
function layout(content){app.innerHTML=`<main class="app"><section class="hero"><h1>${esc(settings.companyName)}</h1><p>MemberHub 會員管理系統｜快速登記、管理及匯出會員資料</p></section>${content}</main>${nav()}`}
function render(){({home,register,membersPage,settingsPage,previewPage,detailPage})[page==='members'?'membersPage':page]()} 
function home(){const month=ym();const recent=[...members].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);layout(`<div class="card"><h2 class="title">首頁</h2><div class="grid grid3"><div class="stat"><span class="muted">會員總數</span><br><b>${members.length}</b></div><div class="stat"><span class="muted">本月新增</span><br><b>${members.filter(m=>ym(m.createdAt)===month).length}</b></div><div class="stat"><span class="muted">今日日期</span><br><b style="font-size:18px">${today()}</b></div></div><div class="actions" style="margin-top:14px"><button onclick="go('register')">新會員登記</button><button class="secondary" onclick="go('members')">會員管理</button><button class="ghost" onclick="go('settings')">設定</button></div></div><div class="card"><h2 class="title">最近新增會員</h2>${recent.length?recent.map(m=>`<div class="member-row"><div><b>${esc(m.chineseName||m.name||'未命名')}</b><br><span class="muted">${esc(m.memberNumber)}</span></div><span class="badge">${esc((m.createdAt||'').slice(0,10))}</span></div>`).join(''):'<p class="muted">未有會員紀錄</p>'}</div>`)}
function memberForm(data={}){const no=data.memberNumber||nextNo();return `<form id="regForm" class="grid2" onsubmit="submitForm(event)">
<div class="field"><label>會員編號</label><input name="memberNumber" value="${esc(no)}" ${settings.manualNumber?'':'readonly'} required></div>
<div class="field"><label>中文姓名</label><input name="chineseName" value="${esc(data.chineseName||data.name||'')}" required></div>
<div class="field"><label>英文姓名</label><input name="englishName" value="${esc(data.englishName||'')}"></div>
<div class="field"><label>性別</label><select name="gender" required><option value="">請選擇</option><option ${data.gender==='男'?'selected':''}>男</option><option ${data.gender==='女'?'selected':''}>女</option></select></div>
<div class="field"><label>出生日月年</label><input name="dateOfBirth" type="date" value="${esc(data.dateOfBirth||'')}" required></div>
<div class="field"><label>身份證號碼</label><input name="hkid" value="${esc(data.hkid||'')}"></div>
<div class="field"><label>電話</label><input name="phone" value="${esc(data.phone||'')}" required></div>
<div class="field"><label>電郵</label><input name="email" type="email" value="${esc(data.email||'')}"></div>
<div class="field" style="grid-column:1/-1"><label>住址</label><textarea name="address">${esc(data.address||'')}</textarea></div>
<div class="field"><label>緊急聯絡人姓名</label><input name="emergencyContactName" value="${esc(data.emergencyContactName||'')}"></div>
<div class="field"><label>緊急聯絡人電話</label><input name="emergencyContactPhone" value="${esc(data.emergencyContactPhone||'')}"></div>
<div class="field" style="grid-column:1/-1"><label><input type="checkbox" name="declaration1Checked" ${data.declaration1Checked?'checked':''} required> 聲明欄1：${esc(settings.declaration1)}</label></div>
<div class="field" style="grid-column:1/-1"><label><input type="checkbox" name="declaration2Checked" ${data.declaration2Checked?'checked':''} required> 聲明欄2：${esc(settings.declaration2)}</label></div>
<div class="field" style="grid-column:1/-1"><label>個人近照（相片上載）</label><input name="photo" type="file" accept="image/*" onchange="photoToBase64(event)"><input type="hidden" name="photoImage" value="${esc(data.photoImage||'')}"><div id="photoPreview">${data.photoImage?`<img class="photo" src="${data.photoImage}">`:''}</div></div>
<div class="actions" style="grid-column:1/-1"><button type="button" class="ghost" onclick="go('home')">返回</button><button type="reset" class="secondary">清空</button><button type="submit">確認</button></div></form>`}
function register(){layout(`<div class="card"><h2 class="title">新會員登記</h2><p class="muted">完成輸入後按「確認」，系統會產生 A4 預覽並進行電子簽署。</p>${memberForm()}</div>`)}
function photoToBase64(e){const f=e.target.files[0];if(!f)return;if(f.size>2.5*1024*1024){alert('相片太大，建議使用 2.5MB 以下圖片');e.target.value='';return}const r=new FileReader();r.onload=()=>{document.querySelector('[name=photoImage]').value=r.result;$('#photoPreview').innerHTML=`<img class="photo" src="${r.result}">`};r.readAsDataURL(f)}
function formData(form){const fd=new FormData(form);return {id:editing?.id||crypto.randomUUID(),memberNumber:fd.get('memberNumber').trim(),chineseName:fd.get('chineseName').trim(),name:fd.get('chineseName').trim(),englishName:fd.get('englishName').trim(),gender:fd.get('gender'),dateOfBirth:fd.get('dateOfBirth'),age:age(fd.get('dateOfBirth')),hkid:fd.get('hkid').trim(),phone:fd.get('phone').trim(),email:fd.get('email').trim(),address:fd.get('address').trim(),emergencyContactName:fd.get('emergencyContactName').trim(),emergencyContactPhone:fd.get('emergencyContactPhone').trim(),declaration1:settings.declaration1,declaration2:settings.declaration2,declaration1Checked:!!fd.get('declaration1Checked'),declaration2Checked:!!fd.get('declaration2Checked'),photoImage:fd.get('photoImage'),signatureImage:editing?.signatureImage||'',applicantName:fd.get('chineseName').trim(),signedDate:today(),createdAt:editing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),duplicateNumber:false}}
function submitForm(e){e.preventDefault();const m=formData(e.target);const duplicate=members.some(x=>x.memberNumber===m.memberNumber&&x.id!==m.id);if(duplicate&&!confirm('會員編號已存在，仍然繼續？'))return;preview=m;page='previewPage';render();setTimeout(initPad,50)}
function previewTable(m,signature=m.signatureImage){return `<div id="pdfArea" class="form-preview"><h2>${esc(settings.companyName)} 會員登記表</h2><div style="display:flex;gap:12px;align-items:flex-start"><div style="flex:1"><div class="preview-grid"><div><b>會員編號</b>${esc(m.memberNumber)}</div><div><b>登記日期</b>${esc((m.createdAt||new Date().toISOString()).slice(0,10))}</div><div><b>中文姓名</b>${esc(m.chineseName)}</div><div><b>英文姓名</b>${esc(m.englishName)}</div><div><b>性別</b>${esc(m.gender)}</div><div><b>出生日月年</b>${esc(m.dateOfBirth)}（${esc(m.age)}歲）</div><div><b>身份證號碼</b>${esc(m.hkid)}</div><div><b>電話</b>${esc(m.phone)}</div><div><b>電郵</b>${esc(m.email)}</div><div><b>緊急聯絡人</b>${esc(m.emergencyContactName)} ${esc(m.emergencyContactPhone)}</div><div style="grid-column:1/-1"><b>住址</b>${esc(m.address)}</div></div></div>${m.photoImage?`<img class="photo" src="${m.photoImage}">`:''}</div><div class="declaration"><b>聲明欄1：</b> ${esc(m.declaration1||settings.declaration1)}\n${m.declaration1Checked?'☑':'☐'} 本人已閱讀並同意上述聲明。\n\n<b>聲明欄2：</b> ${esc(m.declaration2||settings.declaration2)}\n${m.declaration2Checked?'☑':'☐'} 本人已閱讀並同意上述聲明。</div><div class="preview-grid" style="margin-top:8px"><div><b>申請人姓名</b>${esc(m.applicantName||m.chineseName)}</div><div><b>日期</b>${esc(m.signedDate||today())}</div></div><div class="sigbox">${signature?`<img src="${signature}">`:'未簽署'}</div></div>`}
function previewPage(){layout(`<div class="card"><h2 class="title">PDF 表格預覽及電子簽署</h2>${previewTable(preview,lockedSignature)}<div class="card no-print"><h3>電子簽署</h3><canvas id="sigPad" class="signature-pad"></canvas><div class="actions" style="margin-top:10px"><button class="secondary" onclick="clearPad()">清除簽名</button><button class="ok" onclick="confirmSig()">確認簽署</button></div><p class="muted">確認簽署後，簽名會固定顯示於 PDF 預覽及下載版本。</p></div><div class="actions no-print"><button class="ghost" onclick="page='register';render()">返回修改</button><button onclick="savePreview()" ${signatureReady?'':'disabled'}>完成登記</button><button class="secondary" onclick="downloadPdf()" ${signatureReady?'':'disabled'}>下載 PDF</button></div></div>`)}
let ctx,drawing=false;
function initPad(){const c=$('#sigPad');if(!c)return;const r=c.getBoundingClientRect();c.width=r.width*2;c.height=r.height*2;ctx=c.getContext('2d');ctx.scale(2,2);ctx.lineWidth=2.5;ctx.lineCap='round';ctx.strokeStyle='#111';['mousedown','touchstart'].forEach(ev=>c.addEventListener(ev,start,{passive:false}));['mousemove','touchmove'].forEach(ev=>c.addEventListener(ev,move,{passive:false}));['mouseup','mouseleave','touchend'].forEach(ev=>c.addEventListener(ev,end,{passive:false}))}
function pos(e){const c=$('#sigPad'),r=c.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}
function start(e){e.preventDefault();drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)}function move(e){if(!drawing)return;e.preventDefault();const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()}function end(){drawing=false}
function clearPad(){const c=$('#sigPad');ctx.clearRect(0,0,c.width,c.height);lockedSignature='';signatureReady=false;previewPage()}
function confirmSig(){const c=$('#sigPad');lockedSignature=c.toDataURL('image/png');signatureReady=true;preview.signatureImage=lockedSignature;previewPage()}
function savePreview(){if(!signatureReady)return alert('請先確認簽署');const exists=members.some(m=>m.memberNumber===preview.memberNumber&&m.id!==preview.id);preview.duplicateNumber=exists;members.push(preview);save(LS_MEMBERS,members);if(!settings.manualNumber)settings.currentSequence=(settings.currentSequence||settings.startNumber||1)+1;save(LS_SETTINGS,settings);alert('會員已儲存');go('members')}
function membersPage(){const q=(window._q||'').toLowerCase();const list=members.filter(m=>[m.chineseName,m.englishName,m.memberNumber,m.phone,m.hkid].join(' ').toLowerCase().includes(q));layout(`<div class="card"><h2 class="title">會員管理</h2><div class="field"><label>快速搜尋</label><input placeholder="姓名 / 會員編號 / 電話 / 身份證" value="${esc(window._q||'')}" oninput="window._q=this.value;render()"></div>${list.map(m=>`<div class="member-row"><div style="display:flex;gap:10px;align-items:center">${m.photoImage?`<img class="photo small" src="${m.photoImage}">`:''}<div><b>${esc(m.chineseName||m.name)}</b><br><span class="muted">${esc(m.memberNumber)}</span> ${m.duplicateNumber?'<span class="badge">編號重複</span>':''}</div></div><div class="actions"><button class="secondary" onclick="viewMember('${m.id}')">查看</button><button class="danger" onclick="deleteMember('${m.id}')">刪除</button></div></div>`).join('')||'<p class="muted">未有會員</p>'}</div>`)}
function askPass(){const p=prompt('請輸入系統密碼');return p===settings.password}
function viewMember(id){if(!askPass())return alert('密碼錯誤');editing=members.find(m=>m.id===id);page='detailPage';render()}
function deleteMember(id){if(!askPass())return alert('密碼錯誤');if(confirm('確定刪除此會員？')){members=members.filter(m=>m.id!==id);save(LS_MEMBERS,members);render()}}
function detailPage(){const m=editing;layout(`<div class="card"><h2 class="title">會員資料</h2>${previewTable(m,m.signatureImage)}<div class="actions no-print" style="margin-top:12px"><button onclick="enableEdit('${m.id}')">更改資料</button><button class="secondary" onclick="downloadPdf()">下載 PDF</button><button class="ghost" onclick="go('members')">返回</button></div><div id="editBox" class="hidden card no-print"><h3>修改會員資料</h3>${memberForm(m)}</div></div>`)}
function enableEdit(){document.getElementById('editBox').classList.remove('hidden');window.scrollTo(0,document.body.scrollHeight)}
function saveEdited(e){e.preventDefault()}
function downloadPdf(){window.print()}
function settingsPage(){layout(`<div class="card"><h2 class="title">設定</h2><form onsubmit="saveSettings(event)" class="grid2"><div class="field"><label>公司名稱</label><input name="companyName" value="${esc(settings.companyName)}"></div><div class="field"><label>系統密碼</label><input name="password" value="${esc(settings.password)}"></div><div class="field"><label><input type="checkbox" name="manualNumber" ${settings.manualNumber?'checked':''}> 人手更改會員編號</label></div><div class="field"><label>會員編號前綴</label><input name="prefix" value="${esc(settings.prefix)}"></div><div class="field"><label>起始號碼</label><input name="startNumber" type="number" value="${esc(settings.startNumber)}"></div><div class="field"><label>目前流水號</label><input name="currentSequence" type="number" value="${esc(settings.currentSequence)}"></div><div class="field"><label><input type="checkbox" name="includeYear" ${settings.includeYear?'checked':''}> 加入年份</label></div><div class="field"><label><input type="checkbox" name="includeMonth" ${settings.includeMonth?'checked':''}> 加入月份</label></div><div class="field" style="grid-column:1/-1"><label>聲明欄1（自訂）</label><textarea name="declaration1">${esc(settings.declaration1)}</textarea></div><div class="field" style="grid-column:1/-1"><label>聲明欄2（自訂）</label><textarea name="declaration2">${esc(settings.declaration2)}</textarea></div><div class="notice" style="grid-column:1/-1">下一個會員編號：${esc(nextNo()||'由用戶人手輸入')}</div><div class="actions" style="grid-column:1/-1"><button>儲存設定</button><button type="button" class="secondary" onclick="backup()">系統資料備份</button><label class="ghost" style="padding:12px 16px;border-radius:14px;cursor:pointer">新資料匯入<input type="file" accept=".json" style="display:none" onchange="importData(event)"></label></div></form></div>`)}
function saveSettings(e){e.preventDefault();const f=new FormData(e.target);settings={...settings,companyName:f.get('companyName'),password:f.get('password'),manualNumber:!!f.get('manualNumber'),prefix:f.get('prefix')||'MEM',startNumber:+f.get('startNumber')||1,currentSequence:+f.get('currentSequence')||1,includeYear:!!f.get('includeYear'),includeMonth:!!f.get('includeMonth'),declaration1:f.get('declaration1'),declaration2:f.get('declaration2')};save(LS_SETTINGS,settings);alert('設定已儲存');render()}
function backup(){const blob=new Blob([JSON.stringify({settings,members,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MemberHub備份_${today()}.json`;a.click()}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);const incoming=data.members||[];const existingNos=new Set(members.map(m=>m.memberNumber));const merged=incoming.map(m=>({...m,id:crypto.randomUUID(),duplicateNumber:existingNos.has(m.memberNumber)||members.some(x=>x.memberNumber===m.memberNumber)}));members=[...members,...merged];save(LS_MEMBERS,members);alert(`已匯入 ${merged.length} 份會員資料。不會覆蓋舊資料；如有會員編號重複，已標記提醒。`);go('members')}catch(err){alert('匯入失敗：檔案格式不正確')}};r.readAsText(f)}
// Override submit when editing detail
const oldSubmit=submitForm;submitForm=function(e){e.preventDefault();const m=formData(e.target);if(editing){if(!askPass())return alert('密碼錯誤，未能修改');m.signatureImage=editing.signatureImage;m.createdAt=editing.createdAt;m.updatedAt=new Date().toISOString();const dup=members.some(x=>x.memberNumber===m.memberNumber&&x.id!==m.id);m.duplicateNumber=dup;members=members.map(x=>x.id===m.id?m:x);save(LS_MEMBERS,members);editing=m;alert('會員資料已更新');page='detailPage';render();return}oldSubmit(e)}
render();
