const LS_MEMBERS='memberhub_members_v7';
const LS_SETTINGS='memberhub_settings_v7';
const defaultSettings={companyName:'MemberHub',password:'1234',manualNumber:false,prefix:'M',startNumber:1,currentSequence:1,includeYear:false,includeMonth:false,declaration1:'本人確認以上資料正確無誤。',declaration2:'本人同意貴機構按相關私隱政策處理會員資料。'};
let state={page:'home',members:load(LS_MEMBERS,[]),settings:load(LS_SETTINGS,defaultSettings),draft:null,editing:null,pdfMember:null,toast:''};
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}
function save(){localStorage.setItem(LS_MEMBERS,JSON.stringify(state.members));localStorage.setItem(LS_SETTINGS,JSON.stringify(state.settings));}
function $(id){return document.getElementById(id)}
function esc(s=''){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function ym(d){return (d||today()).slice(0,7)}
function uid(){return 'm_'+Date.now()+'_'+Math.random().toString(16).slice(2)}
function calcAge(d){if(!d)return'';const b=new Date(d),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()==b.getMonth()&&n.getDate()<b.getDate()))a--;return a>=0?a:''}
function nextNo(){const s=state.settings;let parts=[]; if(s.includeYear)parts.push(new Date().getFullYear()); if(s.includeMonth)parts.push(String(new Date().getMonth()+1).padStart(2,'0')); parts.push(String(s.currentSequence||s.startNumber||1).padStart(4,'0')); return [s.prefix||'M',...parts].filter(Boolean).join('-')}
function setPage(p){state.page=p; state.editing=null; state.pdfMember=null; render();}
function needPass(msg='請輸入系統密碼'){const p=prompt(msg); if(p===state.settings.password)return true; alert('密碼錯誤'); return false;}
function toast(t){state.toast=t; render(); setTimeout(()=>{state.toast='';render()},1500)}
function imageToData(file,cb){if(!file){cb('');return} const r=new FileReader(); r.onload=()=>cb(r.result); r.readAsDataURL(file)}
function baseMember(){return {id:uid(),memberNumber:state.settings.manualNumber?'':nextNo(),chineseName:'',englishName:'',gender:'男',dateOfBirth:'',hkid:'',phone:'',email:'',address:'',emergencyContactName:'',emergencyContactPhone:'',declaration1:false,declaration2:false,photo:'',signatureImage:'',applicantName:'',signedDate:'',duplicateNumber:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function validate(m){if(!m.memberNumber)return'請輸入會員編號'; if(!m.chineseName)return'請輸入中文姓名'; if(!m.phone)return'請輸入電話'; if(!m.dateOfBirth)return'請輸入出生日期'; if(!m.declaration1||!m.declaration2)return'請勾選聲明欄'; return ''}
function render(){const app=$('app'); app.innerHTML=`<main class="app">${state.toast?`<div class="notice">${esc(state.toast)}</div>`:''}${renderPage()}</main>${tabs()}${state.pdfMember?pdfModal(state.pdfMember):''}`; afterRender();}
function tabs(){return `<nav class="tabs"><button class="tab ${state.page==='home'?'active':''}" onclick="setPage('home')"><i>🏠</i>首頁</button><button class="tab ${state.page==='register'?'active':''}" onclick="setPage('register')"><i>➕</i>登記</button><button class="tab ${state.page==='members'?'active':''}" onclick="setPage('members')"><i>👥</i>會員</button><button class="tab ${state.page==='settings'?'active':''}" onclick="openSettings()"><i>⚙️</i>設定</button></nav>`}
function renderPage(){if(state.page==='register')return registerPage(); if(state.page==='members')return membersPage(); if(state.page==='settings')return settingsPage(); return homePage()}
function homePage(){const month=ym(today());const recent=[...state.members].reverse().slice(0,3);return `<section class="hero"><div class="brand"><div class="logo">🪪</div><div><h1>${esc(state.settings.companyName)}</h1><p class="sub">MemberHub 會員管理系統</p></div></div><div class="stats"><div class="stat"><span>總會員</span><b>${state.members.length}</b></div><div class="stat"><span>本月新增</span><b>${state.members.filter(m=>ym(m.createdAt)===month).length}</b></div><div class="stat"><span>下一編號</span><b style="font-size:18px">${esc(nextNo())}</b></div><div class="stat"><span>今天</span><b style="font-size:18px">${today()}</b></div></div></section><section class="card"><div class="quick"><button class="bigBtn pink" onclick="setPage('register')"><span>✨</span>新會員</button><button class="bigBtn mint" onclick="setPage('members')"><span>🔎</span>會員管理</button><button class="bigBtn lav" onclick="openSettings()"><span>⚙️</span>設定</button></div></section><section class="card"><div class="cardTitle"><h3>最近新增</h3></div>${recent.length?recent.map(memberMini).join(''):'<p class="muted">未有會員資料</p>'}</section>`}
function registerPage(){const m=state.draft||baseMember(); state.draft=m;return `<section class="card"><div class="cardTitle"><h2>新增會員</h2><span class="pill">Mobile First</span></div><div class="actions"><button class="btn sky" onclick="downloadTemplate()">📥 下載範本 Excel</button><label class="btn mint">📤 Excel 批量匯入<input type="file" accept=".xlsx,.xls,.csv" class="hide" onchange="importExcel(this.files[0])"></label></div><form id="regForm" class="formGrid" onsubmit="submitRegister(event)">${formFields(m,true)}<div class="field wide"><label>個人近照</label><input type="file" accept="image/*" onchange="imageToData(this.files[0],d=>{state.draft.photo=d;render()})">${m.photo?`<div class="avatar" style="margin-top:10px;width:90px;height:90px"><img src="${m.photo}"></div>`:''}</div><div class="actions wide"><button class="btn pink" type="submit">確認並簽署</button><button class="btn soft" type="button" onclick="state.draft=baseMember();render()">清空</button></div></form></section>`}
function formFields(m,editingNo=false){return `${field('會員編號','memberNumber',m.memberNumber,state.settings.manualNumber||editingNo?'text':'text',!state.settings.manualNumber&&!editingNo)}${field('中文姓名','chineseName',m.chineseName)}${field('英文姓名','englishName',m.englishName)}<div class="field"><label>性別</label><select name="gender"><option ${m.gender==='男'?'selected':''}>男</option><option ${m.gender==='女'?'selected':''}>女</option></select></div>${field('出生日月年','dateOfBirth',m.dateOfBirth,'date')}${field('身份證號碼','hkid',m.hkid)}${field('電話','phone',m.phone,'tel')}${field('電郵','email',m.email,'email')}${field('住址','address',m.address,'textarea','',true)}${field('緊急聯絡人姓名','emergencyContactName',m.emergencyContactName)}${field('緊急聯絡人電話','emergencyContactPhone',m.emergencyContactPhone,'tel')}<label class="field wide"><input type="checkbox" name="declaration1" ${m.declaration1?'checked':''} style="width:auto"> ${esc(state.settings.declaration1)}</label><label class="field wide"><input type="checkbox" name="declaration2" ${m.declaration2?'checked':''} style="width:auto"> ${esc(state.settings.declaration2)}</label>`}
function field(label,name,value,type='text',disabled=false,wide=false){return `<div class="field ${wide?'wide':''}"><label>${label}</label>${type==='textarea'?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${disabled?'readonly':''}>`}</div>`}
function collect(form,m){const fd=new FormData(form); ['memberNumber','chineseName','englishName','gender','dateOfBirth','hkid','phone','email','address','emergencyContactName','emergencyContactPhone'].forEach(k=>m[k]=fd.get(k)||''); m.declaration1=!!fd.get('declaration1'); m.declaration2=!!fd.get('declaration2'); m.applicantName=m.chineseName; m.signedDate=today(); return m}
function submitRegister(e){e.preventDefault();let m=collect(e.target,state.draft); const err=validate(m); if(err)return alert(err); if(state.members.some(x=>x.memberNumber===m.memberNumber))m.duplicateNumber=true; state.draft=m; showSignature(m,'new')}
function showSignature(m,mode){state.signMode=mode; state.signMember=m; state.page='signature'; render()}
function signaturePage(){return ''}
function afterRender(){if(state.page==='signature')setupSign()}
function renderPage_old(){}
const _renderPage=renderPage;
renderPage=function(){if(state.page==='signature')return signPage();return _renderPage()}
function signPage(){const m=state.signMember;return `<section class="card"><div class="cardTitle"><h2>PDF 預覽及電子簽署</h2><button class="btn soft" onclick="state.page='register';render()">返回</button></div><div class="pdfSheet" id="previewSheet">${pdfContent(m)}</div><div class="card"><h3>電子簽署</h3><p class="muted">請在下方簽名，然後按「確認簽署」。</p><canvas id="sigCanvas" width="520" height="160" style="width:100%;height:160px;background:#fff;border:2px dashed #ffb1c8;border-radius:18px;touch-action:none"></canvas><div class="actions"><button class="btn soft" onclick="clearSig()">清除簽名</button><button class="btn pink" onclick="confirmSig()">確認簽署並儲存</button></div></div></section>`}
let sigCtx, drawing=false;
function setupSign(){const c=$('sigCanvas'); if(!c)return; sigCtx=c.getContext('2d'); sigCtx.lineWidth=3; sigCtx.lineCap='round'; sigCtx.strokeStyle='#111'; const pos=e=>{const r=c.getBoundingClientRect(),t=e.touches?e.touches[0]:e; return {x:(t.clientX-r.left)*c.width/r.width,y:(t.clientY-r.top)*c.height/r.height}}; const start=e=>{drawing=true;const p=pos(e);sigCtx.beginPath();sigCtx.moveTo(p.x,p.y);e.preventDefault()}; const move=e=>{if(!drawing)return;const p=pos(e);sigCtx.lineTo(p.x,p.y);sigCtx.stroke();e.preventDefault()}; const end=()=>drawing=false; c.onmousedown=start;c.onmousemove=move;window.onmouseup=end;c.ontouchstart=start;c.ontouchmove=move;c.ontouchend=end;}
function clearSig(){const c=$('sigCanvas'); sigCtx.clearRect(0,0,c.width,c.height)}
function confirmSig(){const c=$('sigCanvas'); const img=c.toDataURL('image/png'); let m=state.signMember; m.signatureImage=img; m.updatedAt=new Date().toISOString(); if(state.signMode==='new'){ state.members.push(m); if(!state.settings.manualNumber)state.settings.currentSequence=(state.settings.currentSequence||state.settings.startNumber||1)+1; state.draft=baseMember(); } else {state.members=state.members.map(x=>x.id===m.id?m:x)} save(); state.pdfMember=m; state.page='members'; toast('已儲存會員及簽名');}
function membersPage(){const q=(state.q||'').toLowerCase();const list=state.members.filter(m=>[m.memberNumber,m.chineseName,m.englishName,m.phone,m.hkid].join(' ').toLowerCase().includes(q));return `<section class="card"><div class="cardTitle"><h2>會員管理</h2><span class="pill">${list.length} 位</span></div><input placeholder="搜尋姓名 / 編號 / 電話 / 身份證" value="${esc(state.q||'')}" oninput="state.q=this.value;render()"><div class="actions"><button class="btn sky" onclick="exportMembersExcel()">📊 批量輸出會員 Excel</button></div><p class="muted">Excel 輸出前需輸入系統密碼；工作表會以系統密碼作保護。</p>${list.map(memberCard).join('')||'<p class="muted">沒有會員</p>'}</section>${state.editing?editModal(state.editing):''}`}
function memberMini(m){return `<div class="memberCard"><div style="display:flex;gap:12px;align-items:center"><div class="avatar">${m.photo?`<img src="${m.photo}">`:'👤'}</div><div><b>${esc(m.chineseName||m.englishName)}</b><div class="muted">${esc(m.memberNumber)}</div></div></div></div>`}
function memberCard(m){return `<div class="memberCard"><div style="display:flex;gap:12px;align-items:center"><div class="avatar">${m.photo?`<img src="${m.photo}"><button class="xPhoto" onclick="deletePhoto('${m.id}')">×</button>`:'👤'}</div><div><b>${esc(m.chineseName||m.englishName)}</b><div class="muted">${esc(m.memberNumber)} ${m.duplicateNumber?'<span class="pill">編號重複</span>':''}</div></div></div><div class="actions" style="margin:0"><button class="btn soft" onclick="viewMember('${m.id}')">查看</button><button class="btn sky" onclick="openPdf('${m.id}')">PDF</button><button class="btn danger" onclick="deleteMember('${m.id}')">刪除</button></div></div>`}
function viewMember(id){if(!needPass('查看會員資料需要密碼'))return; state.editing=JSON.parse(JSON.stringify(state.members.find(m=>m.id===id))); render()}
function deleteMember(id){if(!needPass('刪除會員需要密碼'))return;if(confirm('確定刪除會員？')){state.members=state.members.filter(m=>m.id!==id);save();render()}}
function deletePhoto(id){event.stopPropagation(); if(!needPass('刪除相片需要密碼'))return; state.members=state.members.map(m=>m.id===id?{...m,photo:'',updatedAt:new Date().toISOString()}:m); save(); render()}
function openPdf(id){const m=state.members.find(x=>x.id===id); state.pdfMember=m; render()}
function editModal(m){return `<div class="modal"><div class="modalBox"><div class="cardTitle"><h2>會員資料</h2><button class="btn soft" onclick="state.editing=null;render()">關閉</button></div><form id="editForm" class="formGrid" onsubmit="saveEdit(event)">${formFields(m,true)}<div class="field wide"><label>個人近照</label>${m.photo?`<div class="avatar" style="width:100px;height:100px"><img src="${m.photo}"><button type="button" class="xPhoto" onclick="state.editing.photo='';render()">×</button></div>`:''}<input type="file" accept="image/*" onchange="imageToData(this.files[0],d=>{state.editing.photo=d;render()})"></div><div class="actions wide"><button class="btn pink" type="submit">確認修改</button><button class="btn sky" type="button" onclick="state.pdfMember=state.editing;render()">下載 PDF</button></div></form></div></div>`}
function saveEdit(e){e.preventDefault(); if(!needPass('完成修改需要輸入密碼'))return; let m=collect(e.target,state.editing); m.signatureImage=state.editing.signatureImage; m.photo=state.editing.photo; m.updatedAt=new Date().toISOString(); state.members=state.members.map(x=>x.id===m.id?m:x); save(); state.editing=null; toast('已更新會員資料')}
function pdfContent(m){return `<h2>${esc(state.settings.companyName)} 會員登記表</h2><div style="display:flex;justify-content:space-between;gap:8px;margin-bottom:8px"><div><b>會員編號：</b>${esc(m.memberNumber)}</div><div><b>日期：</b>${esc(m.signedDate||today())}</div></div><div style="display:flex;gap:8px"><div class="pdfGrid" style="flex:1"><div class="pdfBox"><b>中文姓名</b><br>${esc(m.chineseName)}</div><div class="pdfBox"><b>英文姓名</b><br>${esc(m.englishName)}</div><div class="pdfBox"><b>性別</b><br>${esc(m.gender)}</div><div class="pdfBox"><b>出生日期</b><br>${esc(m.dateOfBirth)} ${calcAge(m.dateOfBirth)?`(${calcAge(m.dateOfBirth)}歲)`:''}</div><div class="pdfBox"><b>身份證號碼</b><br>${esc(m.hkid)}</div><div class="pdfBox"><b>電話</b><br>${esc(m.phone)}</div><div class="pdfBox"><b>電郵</b><br>${esc(m.email)}</div><div class="pdfBox"><b>緊急聯絡人</b><br>${esc(m.emergencyContactName)} ${esc(m.emergencyContactPhone)}</div><div class="pdfBox" style="grid-column:1/-1"><b>住址</b><br>${esc(m.address)}</div><div class="pdfBox" style="grid-column:1/-1"><b>聲明一</b><br>☑ ${esc(state.settings.declaration1)}</div><div class="pdfBox" style="grid-column:1/-1"><b>聲明二</b><br>☑ ${esc(state.settings.declaration2)}</div><div class="pdfBox"><b>申請人姓名</b><br>${esc(m.applicantName||m.chineseName)}</div><div class="pdfBox"><b>電子簽署</b><br>${m.signatureImage?`<img class="sig" src="${m.signatureImage}">`:'未簽署'}</div></div>${m.photo?`<div><img class="photoLarge" src="${m.photo}"><div class="muted">個人近照</div></div>`:''}</div>`}
function pdfModal(m){return `<div class="modal"><div class="modalBox"><div class="cardTitle noPrint"><h2>PDF 預覽</h2><button class="btn soft" onclick="state.pdfMember=null;render()">關閉預覽</button></div><div class="pdfSheet">${pdfContent(m)}</div><div class="actions noPrint"><button class="btn pink" onclick="window.print()">下載 / 儲存 PDF</button><button class="btn soft" onclick="state.pdfMember=null;render()">返回會員頁</button></div></div></div>`}
function settingsPage(){const s=state.settings;return `<section class="card"><div class="cardTitle"><h2>設定</h2></div><form class="formGrid" onsubmit="saveSettings(event)">${field('公司名稱','companyName',s.companyName)}${field('系統密碼','password',s.password,'password')}<label class="field wide"><input type="checkbox" name="manualNumber" ${s.manualNumber?'checked':''} style="width:auto"> 啟用人手更改會員編號</label>${field('自動編號前綴','prefix',s.prefix)}${field('起始號碼','startNumber',s.startNumber,'number')}<label class="field"><input type="checkbox" name="includeYear" ${s.includeYear?'checked':''} style="width:auto"> 加入年份</label><label class="field"><input type="checkbox" name="includeMonth" ${s.includeMonth?'checked':''} style="width:auto"> 加入月份</label>${field('聲明欄 1','declaration1',s.declaration1,'textarea','',true)}${field('聲明欄 2','declaration2',s.declaration2,'textarea','',true)}<div class="notice wide">下一個自動會員編號：${esc(nextNo())}</div><div class="actions wide"><button class="btn pink" type="submit">儲存設定</button><button type="button" class="btn sky" onclick="backupData()">系統資料備份</button><label class="btn mint">新資料匯入<input class="hide" type="file" accept=".json" onchange="importBackup(this.files[0])"></label></div></form></section>`}
function openSettings(){if(!state.settings.password||needPass('進入設定需要密碼'))setPage('settings')}
function saveSettings(e){e.preventDefault();const fd=new FormData(e.target);state.settings={...state.settings,companyName:fd.get('companyName'),password:fd.get('password')||'',manualNumber:!!fd.get('manualNumber'),prefix:fd.get('prefix')||'M',startNumber:Number(fd.get('startNumber')||1),includeYear:!!fd.get('includeYear'),includeMonth:!!fd.get('includeMonth'),declaration1:fd.get('declaration1')||'',declaration2:fd.get('declaration2')||''}; if(!state.settings.currentSequence)state.settings.currentSequence=state.settings.startNumber; save(); toast('設定已儲存')}
function backupData(){const blob=new Blob([JSON.stringify({version:'memberhub-v7',settings:state.settings,members:state.members,backupAt:new Date().toISOString()},null,2)],{type:'application/json'});downloadBlob(blob,`MemberHub_backup_${today()}.json`)}
function importBackup(file){if(!file)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); const incoming=data.members||[]; const existing=new Set(state.members.map(m=>m.memberNumber)); const add=incoming.map(m=>({...m,id:uid(),duplicateNumber:existing.has(m.memberNumber)||state.members.some(x=>x.memberNumber===m.memberNumber)})); state.members=[...state.members,...add]; save(); toast(`已匯入 ${add.length} 筆資料`)}catch(e){alert('匯入失敗，請確認檔案格式')}}; r.readAsText(file)}
function downloadTemplate(){const headers=['會員編號','中文姓名','英文姓名','性別','出生日期','身份證號碼','電話','電郵','住址','緊急聯絡人姓名','緊急聯絡人電話']; const rows=[headers,['M0001','陳大文','CHAN Tai Man','男','1980-01-01','A123456(7)','91234567','test@example.com','香港九龍','陳小明','92345678']]; makeWorkbook(rows,'MemberHub_會員批量匯入範本.xlsx')}
function importExcel(file){if(!file)return; const r=new FileReader(); r.onload=e=>{const wb=XLSX.read(new Uint8Array(e.target.result),{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}); const body=rows.slice(1).filter(r=>r.some(Boolean)); const existing=new Set(state.members.map(m=>m.memberNumber)); let added=[]; body.forEach((r,i)=>{let no=r[0]||nextNo(); let m={...baseMember(),memberNumber:String(no),chineseName:String(r[1]||''),englishName:String(r[2]||''),gender:String(r[3]||'男'),dateOfBirth:excelDate(r[4]),hkid:String(r[5]||''),phone:String(r[6]||''),email:String(r[7]||''),address:String(r[8]||''),emergencyContactName:String(r[9]||''),emergencyContactPhone:String(r[10]||''),declaration1:true,declaration2:true,duplicateNumber:existing.has(String(no))||added.some(x=>x.memberNumber===String(no)),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; added.push(m); if(!state.settings.manualNumber && !r[0])state.settings.currentSequence++}); state.members=[...state.members,...added]; save(); toast(`已匯入 ${added.length} 位會員`)}; r.readAsArrayBuffer(file)}
function excelDate(v){if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`} return String(v||'')}
function exportMembersExcel(){if(!needPass('批量輸出會員 Excel 需要輸入系統密碼'))return; const s=state.settings; const rows=[['會員編號','中文姓名','英文姓名','性別','出生日期','年齡','身份證號碼','電話','電郵','住址','緊急聯絡人姓名','緊急聯絡人電話','聲明欄1','聲明欄2','是否有相片','是否有電子簽署','編號重複','建立日期','更新日期']]; state.members.forEach(m=>rows.push([m.memberNumber,m.chineseName,m.englishName,m.gender,m.dateOfBirth,calcAge(m.dateOfBirth),m.hkid,m.phone,m.email,m.address,m.emergencyContactName,m.emergencyContactPhone,m.declaration1?'已同意':'',m.declaration2?'已同意':'',m.photo?'有':'沒有',m.signatureImage?'有':'沒有',m.duplicateNumber?'是':'否',m.createdAt,m.updatedAt])); const wb=XLSX.utils.book_new(); const ws=XLSX.utils.aoa_to_sheet(rows); ws['!cols']=[14,14,20,8,12,8,14,14,24,34,18,18,12,12,10,12,10,22,22].map(w=>({wch:w})); ws['!protect']={password:s.password,selectLockedCells:true,selectUnlockedCells:true,formatCells:false,insertRows:false,deleteRows:false}; XLSX.utils.book_append_sheet(wb,ws,'會員資料'); XLSX.writeFile(wb,`MemberHub_會員資料_${today()}.xlsx`,{bookType:'xlsx',type:'binary'}); alert('Excel 已產生。注意：純前端版本已加入匯出前密碼驗證及工作表保護；如你需要「開檔前輸入密碼」級別的真正加密，需使用後端或桌面版 Excel 加密。')}
function makeWorkbook(rows,name){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'範本');XLSX.writeFile(wb,name)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
render();
