const $ = (s, r=document)=>r.querySelector(s);
const $$ = (s, r=document)=>Array.from(r.querySelectorAll(s));
const LS_MEMBERS='memberhub_members_v15';
const LS_SETTINGS='memberhub_settings_v15';
const oldKeys=['memberhub_members_v14','memberhub_members_v13','memberhub_members_v12','memberhub_members_v11','memberhub_members_v10','memberhub_members_v9','memberhub_members'];
const defaultSettings={companyName:'我的機構',password:'',prefix:'M',digits:4,startNumber:1,currentSequence:1,includeYear:false,includeMonth:false,manualNumber:false,declaration1:'本人確認以上資料真確無誤。',declaration2:'本人同意機構按服務需要保存及使用本人提供的資料。'};
let page='home', draft=null, lockedSig='', editingId=null;
let canvas=null, ctx=null, drawing=false;
function uid(){return 'm_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
function today(){return new Date().toLocaleDateString('zh-HK')}
function nowISO(){return new Date().toISOString()}
function safeParse(v,d){try{return JSON.parse(v)||d}catch{return d}}
function loadSettings(){return {...defaultSettings,...safeParse(localStorage.getItem(LS_SETTINGS),{})}}
function saveSettings(s){localStorage.setItem(LS_SETTINGS,JSON.stringify(s))}
function loadMembers(){let m=safeParse(localStorage.getItem(LS_MEMBERS),null); if(!m){for(const k of oldKeys){const o=safeParse(localStorage.getItem(k),null);if(Array.isArray(o)){m=o;break}}} return Array.isArray(m)?m:[]}
function saveMembers(m){localStorage.setItem(LS_MEMBERS,JSON.stringify(m))}
function pad(n,d){return String(n).padStart(Number(d)||4,'0')}
function nextNo(){const s=loadSettings();let parts=[]; if(s.includeYear)parts.push(new Date().getFullYear()); if(s.includeMonth)parts.push(String(new Date().getMonth()+1).padStart(2,'0')); const serial=pad(Number(s.currentSequence||s.startNumber||1),s.digits); return [s.prefix,...parts,serial].filter(Boolean).join('-')}
function calcAge(d){if(!d)return '';const b=new Date(d);if(isNaN(b))return '';const t=new Date();let a=t.getFullYear()-b.getFullYear();const m=t.getMonth()-b.getMonth();if(m<0||(m===0&&t.getDate()<b.getDate()))a--;return a}
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function requirePassword(msg='請輸入系統密碼'){const s=loadSettings(); if(!s.password){alert('尚未設定密碼，請先到設定頁建立密碼。');page='settings';render();return false} const p=prompt(msg); return p===s.password}
function migrateMember(m){return {id:m.id||uid(),memberNumber:m.memberNumber||m.no||'',chineseName:m.chineseName||m.name||'',englishName:m.englishName||'',gender:m.gender||'',dateOfBirth:m.dateOfBirth||m.dob||'',hkid:m.hkid||'',phone:m.phone||'',email:m.email||'',address:m.address||'',emergencyContactName:m.emergencyContactName||'',emergencyContactPhone:m.emergencyContactPhone||'',declaration1:m.declaration1??true,declaration2:m.declaration2??true,photo:m.photo||'',signatureImage:m.signatureImage||m.signature||'',applicantName:m.applicantName||m.chineseName||m.name||'',signatureDate:m.signatureDate||today(),duplicateNumber:m.duplicateNumber||false,createdAt:m.createdAt||nowISO(),updatedAt:m.updatedAt||nowISO()}}
function normalizeMembers(){const arr=loadMembers().map(migrateMember);saveMembers(arr);return arr}
function header(){const s=loadSettings();return `<div class="hero"><h1>${esc(s.companyName)}</h1><p>MemberHub 會員管理系統｜快速登記、管理及匯出會員資料。</p></div>`}
function nav(){return `<div class="nav"><div class="navin">${[['home','首頁'],['register','登記'],['members','會員'],['settings','設定']].map(([k,t])=>`<button class="${page===k?'active':''}" onclick="go('${k}')">${t}</button>`).join('')}</div></div>`}
window.go=(p)=>{if((p==='members'||p==='settings')&&p!==page){if(!requirePassword())return} page=p; draft=null; lockedSig=''; editingId=null; render()}
function render(){normalizeMembers(); const app=$('#app'); app.innerHTML=`<main class="wrap">${header()}${view()}</main>${nav()}<div id="printArea" class="print-only hidden"></div>`; afterRender()}
function view(){if(page==='register')return viewRegister(); if(page==='preview')return viewPreview(); if(page==='members')return viewMembers(); if(page==='memberDetail')return viewMemberDetail(); if(page==='settings')return viewSettings(); return viewHome()}
function viewHome(){const m=loadMembers();const ym=new Date().toISOString().slice(0,7);const recent=[...m].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,5);return `<div class="grid"><section class="card"><h2>功能</h2><div class="actions"><button onclick="go('register')">新會員登記</button><button class="secondary" onclick="go('members')">會員管理</button><button class="ghost" onclick="go('settings')">設定</button></div></section><section class="card"><h2>今日概況</h2><div class="stats"><div class="stat"><span>會員總數</span><b>${m.length}</b></div><div class="stat"><span>本月新增</span><b>${m.filter(x=>String(x.createdAt).slice(0,7)===ym).length}</b></div></div><p class="pill">今日：${today()}</p></section></div><section class="card"><h2>最近新增會員</h2><div class="member-list">${recent.length?recent.map(x=>`<div class="member-mini"><div><div class="name">${esc(x.chineseName||x.name)} ${x.englishName?`<span class="no">(${esc(x.englishName)})</span>`:''}</div><div class="no">${esc(x.memberNumber)}</div></div><span class="pill">${new Date(x.createdAt).toLocaleDateString('zh-HK')}</span></div>`).join(''):'<p class="notice">暫未有會員資料。</p>'}</div></section>`}
function formFields(data={},disabled=false){const s=loadSettings(); const dis=disabled?'disabled':''; const numberField=s.manualNumber?`<input class="field" name="memberNumber" value="${esc(data.memberNumber||'')}" ${dis} required>`:`<input class="field" name="memberNumber" value="${esc(data.memberNumber||nextNo())}" disabled>`;return `<div class="row two"><label>會員編號 ${numberField}</label><label>中文姓名 <input class="field" name="chineseName" value="${esc(data.chineseName||'')}" ${dis} required></label></div><div class="row two"><label>英文姓名 <input class="field" name="englishName" value="${esc(data.englishName||'')}" ${dis} placeholder="如 CHAN Tai Man"></label><label>性別 <select class="field" name="gender" ${dis} required><option value="">請選擇</option><option ${data.gender==='男'?'selected':''}>男</option><option ${data.gender==='女'?'selected':''}>女</option></select></label></div><div class="row two"><label>出生日月年 <input class="field" type="date" name="dateOfBirth" value="${esc(data.dateOfBirth||'')}" ${dis} required></label><label>身份證號碼 <input class="field" name="hkid" value="${esc(data.hkid||'')}" ${dis} required></label></div><div class="row two"><label>電話 <input class="field" name="phone" value="${esc(data.phone||'')}" ${dis} required></label><label>電郵 <input class="field" type="email" name="email" value="${esc(data.email||'')}" ${dis}></label></div><div class="row"><label>住址 <textarea class="field" name="address" ${dis}>${esc(data.address||'')}</textarea></label></div><div class="row two"><label>緊急聯絡人姓名 <input class="field" name="emergencyContactName" value="${esc(data.emergencyContactName||'')}" ${dis}></label><label>緊急聯絡人電話 <input class="field" name="emergencyContactPhone" value="${esc(data.emergencyContactPhone||'')}" ${dis}></label></div><div class="row two"><label><input type="checkbox" name="declaration1" ${data.declaration1===false?'':'checked'} ${dis}> ${esc(s.declaration1)}</label><label><input type="checkbox" name="declaration2" ${data.declaration2===false?'':'checked'} ${dis}> ${esc(s.declaration2)}</label></div><div class="row"><label>個人近照 ${disabled?'': '<input class="field" type="file" name="photoFile" accept="image/*">'} </label>${data.photo?`<img class="photo" src="${data.photo}" alt="個人近照">`:''}<input type="hidden" name="photo" value="${esc(data.photo||'')}"></div>`}
function viewRegister(){return `<section class="card"><h2>新會員登記</h2><p class="notice">請輸入會員資料。英文姓名及個人近照已加入本版本。</p><form id="regForm">${formFields({})}<div class="actions"><button type="button" class="ghost" onclick="resetReg()">清空</button><button type="submit">確認</button></div></form></section>`}
window.resetReg=()=>{$('#regForm')?.reset()}
async function fileToDataURL(file,maxW=900){return new Promise((res,rej)=>{if(!file)return res('');const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,maxW/img.width);const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.82))};img.onerror=rej;img.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
function dataFromForm(form){const fd=new FormData(form);return {memberNumber:fd.get('memberNumber')||nextNo(),chineseName:fd.get('chineseName')||'',englishName:fd.get('englishName')||'',gender:fd.get('gender')||'',dateOfBirth:fd.get('dateOfBirth')||'',hkid:fd.get('hkid')||'',phone:fd.get('phone')||'',email:fd.get('email')||'',address:fd.get('address')||'',emergencyContactName:fd.get('emergencyContactName')||'',emergencyContactPhone:fd.get('emergencyContactPhone')||'',declaration1:!!fd.get('declaration1'),declaration2:!!fd.get('declaration2'),photo:fd.get('photo')||''}}
function validate(d,ignoreId=null){if(!d.memberNumber||!d.chineseName||!d.gender||!d.dateOfBirth||!d.hkid||!d.phone)return '請填寫會員編號、中文姓名、性別、出生日期、身份證號碼及電話。'; const dup=loadMembers().find(x=>x.memberNumber===d.memberNumber&&x.id!==ignoreId); if(dup && !confirm('會員編號重複，仍然新增／儲存？系統會標記「編號重複」。'))return '請更改會員編號。'; return ''}
function viewPreview(){if(!draft)return `<section class="card"><p>沒有預覽資料。</p></section>`;return `<section class="card"><h2>PDF 表格預覽及電子簽署</h2><div id="pdfPreview">${pdfHTML(draft,false)}</div><div class="card no-print"><h3>電子簽署</h3><canvas id="sigCanvas" class="sigbox"></canvas><div class="row two"><label>申請人姓名 <input class="field" id="applicantName" value="${esc(draft.applicantName||draft.chineseName)}"></label><label>日期 <input class="field" type="date" id="signatureDate" value="${new Date().toISOString().slice(0,10)}"></label></div><div class="actions"><button class="ghost" onclick="clearSig()">清除簽名</button><button class="ok" onclick="confirmSig()">確認簽署</button><button class="secondary" onclick="go('register')">返回修改</button><button onclick="saveDraftMember()" ${lockedSig?'':'disabled'}>完成登記</button><button class="secondary" onclick="downloadPDF(draft)" ${lockedSig?'':'disabled'}>下載 PDF</button></div></div></section>`}
function pdfHTML(m,compact=true){const s=loadSettings();const age=calcAge(m.dateOfBirth);return `<div class="pdfsheet"><h1>${esc(s.companyName)}</h1><h2>會員登記表</h2><div style="display:flex;justify-content:space-between;gap:8mm"><div style="flex:1"><div class="pdfgrid"><div class="pdfitem"><b>會員編號</b>${esc(m.memberNumber)}</div><div class="pdfitem"><b>中文姓名</b>${esc(m.chineseName)}</div><div class="pdfitem"><b>英文姓名</b>${esc(m.englishName)}</div><div class="pdfitem"><b>性別</b>${esc(m.gender)}</div><div class="pdfitem"><b>出生日期</b>${esc(m.dateOfBirth)} ${age!==''?`（${age}歲）`:''}</div><div class="pdfitem"><b>身份證</b>${esc(m.hkid)}</div><div class="pdfitem"><b>電話</b>${esc(m.phone)}</div><div class="pdfitem"><b>電郵</b>${esc(m.email)}</div><div class="pdfitem" style="grid-column:1/-1"><b>住址</b>${esc(m.address)}</div><div class="pdfitem"><b>緊急聯絡人</b>${esc(m.emergencyContactName)}</div><div class="pdfitem"><b>緊急電話</b>${esc(m.emergencyContactPhone)}</div></div></div><div>${m.photo?`<img class="photo big" src="${m.photo}">`:'<div class="photo big" style="display:flex;align-items:center;justify-content:center;color:#94a3b8">相片</div>'}</div></div><div class="pdfdecl"><b>聲明欄 1：</b> ${m.declaration1?'☑':'☐'} ${esc(s.declaration1)}<br><b>聲明欄 2：</b> ${m.declaration2?'☑':'☐'} ${esc(s.declaration2)}</div><div class="pdfsign"><div><b>申請人姓名</b><div class="pdfitem">${esc(m.applicantName||m.chineseName)}</div></div><div><b>日期</b><div class="pdfitem">${esc(m.signatureDate||today())}</div></div><div style="grid-column:1/-1"><b>電子簽署</b><br>${m.signatureImage?`<img class="sigimg" src="${m.signatureImage}">`:'<div style="height:24mm;border-bottom:1px solid #111"></div>'}</div></div></div>`}
function afterRender(){const reg=$('#regForm'); if(reg){reg.onsubmit=async e=>{e.preventDefault();const file=reg.photoFile?.files?.[0];const d=dataFromForm(reg);if(file)d.photo=await fileToDataURL(file); const err=validate(d); if(err){alert(err);return} draft={...d,id:uid(),applicantName:d.chineseName,signatureDate:today(),signatureImage:'',createdAt:nowISO(),updatedAt:nowISO(),duplicateNumber:!!loadMembers().find(x=>x.memberNumber===d.memberNumber)}; page='preview';render()}} if($('#sigCanvas'))initSig(); const edit=$('#editForm'); if(edit){edit.onsubmit=async e=>{e.preventDefault();await saveEdit(edit)}}}
function initSig(){canvas=$('#sigCanvas');ctx=canvas.getContext('2d');const resize=()=>{const r=canvas.getBoundingClientRect();const img=ctx.getImageData(0,0,canvas.width||1,canvas.height||1);canvas.width=Math.max(300,Math.floor(r.width*2));canvas.height=Math.floor(r.height*2);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.lineCap='round'};resize();const pos=e=>{const r=canvas.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*2,y:(t.clientY-r.top)*2}};const start=e=>{e.preventDefault();drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};const move=e=>{if(!drawing)return;e.preventDefault();const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};const end=()=>{drawing=false};canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);window.addEventListener('mouseup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end)}
window.clearSig=()=>{if(ctx&&canvas){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);lockedSig='';}}
window.confirmSig=()=>{if(!canvas)return; lockedSig=canvas.toDataURL('image/png'); draft.signatureImage=lockedSig; draft.applicantName=$('#applicantName').value||draft.chineseName; draft.signatureDate=$('#signatureDate').value||today(); alert('已確認簽署，PDF 預覽已更新。'); render()}
window.saveDraftMember=()=>{if(!lockedSig){alert('請先確認簽署。');return}const s=loadSettings();const arr=loadMembers();arr.push(migrateMember(draft));saveMembers(arr); if(!s.manualNumber){s.currentSequence=Number(s.currentSequence||s.startNumber||1)+1;saveSettings(s)} alert('會員已儲存。');page='members';render()}
function viewMembers(){const m=loadMembers();const q=(window.memberQ||'').toLowerCase();const filtered=m.filter(x=>[x.memberNumber,x.chineseName,x.englishName,x.phone,x.hkid].join(' ').toLowerCase().includes(q));return `<section class="card"><h2>會員管理</h2><input class="field" placeholder="搜尋姓名／會員編號／電話／身份證" value="${esc(window.memberQ||'')}" oninput="window.memberQ=this.value;render()"><div class="member-list" style="margin-top:12px">${filtered.map(x=>`<div class="member-mini"><div><div class="name">${esc(x.chineseName||x.name)} ${x.duplicateNumber?'<span class="pill">編號重複</span>':''}</div><div class="no">${esc(x.memberNumber)} ${x.englishName?`｜${esc(x.englishName)}`:''}</div></div><div class="actions"><button class="secondary" onclick="openMember('${x.id}')">查看</button><button class="danger" onclick="deleteMember('${x.id}')">刪除</button></div></div>`).join('')||'<p class="notice">沒有會員資料。</p>'}</div></section>`}
window.openMember=id=>{if(!requirePassword('請輸入密碼查看會員資料'))return; editingId=id; page='memberDetail'; render()}
window.deleteMember=id=>{if(!requirePassword('請輸入密碼刪除會員'))return;if(!confirm('確定刪除此會員？'))return;saveMembers(loadMembers().filter(x=>x.id!==id));render()}
function viewMemberDetail(){const m=loadMembers().find(x=>x.id===editingId);if(!m)return `<section class="card">找不到會員。</section>`;return `<section class="card"><h2>會員資料</h2><form id="editForm">${formFields(m,false)}<div class="actions"><button type="submit">確認修改</button><button type="button" class="secondary" onclick="downloadPDFById('${m.id}')">下載 PDF</button><button type="button" class="ghost" onclick="go('members')">返回</button></div></form><div style="margin-top:16px">${pdfHTML(m)}</div></section>`}
async function saveEdit(form){if(!requirePassword('請輸入密碼確認更改'))return;const file=form.photoFile?.files?.[0];const d=dataFromForm(form);if(file)d.photo=await fileToDataURL(file); else d.photo=form.photo.value;const err=validate(d,editingId);if(err){alert(err);return}const arr=loadMembers();const i=arr.findIndex(x=>x.id===editingId);arr[i]={...arr[i],...d,updatedAt:nowISO(),duplicateNumber:!!arr.find(x=>x.memberNumber===d.memberNumber&&x.id!==editingId)};saveMembers(arr);alert('已更新會員資料。');render()}
window.downloadPDFById=id=>{const m=loadMembers().find(x=>x.id===id); if(m)downloadPDF(m)}
window.downloadPDF=(m)=>{const mm={...m,signatureImage:m.signatureImage||lockedSig};const html=`<!doctype html><html><head><meta charset="utf-8"><title>會員登記表</title><link rel="stylesheet" href="style.css"></head><body>${pdfHTML(mm)}</body></html>`;const w=window.open('','_blank');w.document.write(html);w.document.close();setTimeout(()=>{w.focus();w.print()},500)}
function viewSettings(){const s=loadSettings();return `<section class="card"><h2>設定</h2><form id="setForm"><div class="row two"><label>公司名稱 <input class="field" name="companyName" value="${esc(s.companyName)}"></label><label>系統密碼 <input class="field" name="password" type="password" value="${esc(s.password)}"></label></div><div class="row three"><label>前綴 <input class="field" name="prefix" value="${esc(s.prefix)}"></label><label>起始號碼 <input class="field" type="number" name="startNumber" value="${esc(s.startNumber)}"></label><label>流水號位數 <input class="field" type="number" name="digits" value="${esc(s.digits)}"></label></div><div class="row"><label><input type="checkbox" name="manualNumber" ${s.manualNumber?'checked':''}> 人手更改會員編號</label><label><input type="checkbox" name="includeYear" ${s.includeYear?'checked':''}> 自動編號加入年份</label><label><input type="checkbox" name="includeMonth" ${s.includeMonth?'checked':''}> 自動編號加入月份</label></div><p class="notice">下一個會員編號：${esc(nextNo())}</p><div class="row"><label>聲明欄 1 <textarea class="field" name="declaration1">${esc(s.declaration1)}</textarea></label></div><div class="row"><label>聲明欄 2 <textarea class="field" name="declaration2">${esc(s.declaration2)}</textarea></label></div><div class="actions"><button type="submit">儲存設定</button></div></form></section><section class="card"><h2>系統資料備份及匯入</h2><p class="notice">備份會匯出會員資料及設定。匯入時不會覆蓋舊會員；如會員編號重複，會照樣新增並標記「編號重複」。</p><div class="actions"><button onclick="backupData()">下載系統備份</button><label class="field" style="max-width:320px">匯入備份 JSON <input type="file" accept="application/json" onchange="importData(this.files[0])"></label></div></section>`}
function settingsSubmit(){const f=$('#setForm'); if(!f)return; f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);const old=loadSettings();const s={...old,companyName:fd.get('companyName'),password:fd.get('password'),prefix:fd.get('prefix'),startNumber:Number(fd.get('startNumber')||1),digits:Number(fd.get('digits')||4),includeYear:!!fd.get('includeYear'),includeMonth:!!fd.get('includeMonth'),manualNumber:!!fd.get('manualNumber'),declaration1:fd.get('declaration1'),declaration2:fd.get('declaration2')}; if(!old.currentSequence || Number(old.currentSequence)<Number(s.startNumber))s.currentSequence=s.startNumber; saveSettings(s);alert('設定已儲存');render()}}
const oldAfter=afterRender; afterRender=function(){oldAfter();settingsSubmit()}
window.backupData=()=>{const data={version:'memberhub_v15',exportedAt:nowISO(),settings:loadSettings(),members:loadMembers()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MemberHub_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
window.importData=file=>{if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);const incoming=(data.members||[]).map(migrateMember);const current=loadMembers();const nums=new Set(current.map(x=>x.memberNumber));let dup=0;incoming.forEach(x=>{if(nums.has(x.memberNumber)){x.duplicateNumber=true;dup++}current.push({...x,id:uid(),createdAt:x.createdAt||nowISO(),updatedAt:nowISO()});nums.add(x.memberNumber)});saveMembers(current);alert(`已匯入 ${incoming.length} 個會員。${dup?`其中 ${dup} 個會員編號重複，已標記提醒。`:''}`);render()}catch(e){alert('匯入失敗，請確認 JSON 備份檔格式。')}};r.readAsText(file)}
render();
